FROM node:20-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY backend/package*.json ./
RUN npm ci --omit=dev

# Copy source code
COPY backend/ .

# Generate Prisma client
RUN npx prisma generate

EXPOSE 4000
ENV PORT=4000
CMD ["node", "src/index.js"]
